const now = new Date();
const isoFromNow = (hours) => new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();

export const mockUsers = [
  { id: "t1", email: "teacher@demo.com", password: "123456", role: "teacher", name: "Riya Sharma" },
  { id: "t2", email: "teacher2@demo.com", password: "123456", role: "teacher", name: "Amit Verma" },
  { id: "p1", email: "principal@demo.com", password: "123456", role: "principal", name: "Dr. Mehta" }
];

export const subjects = ["Mathematics", "Science", "English", "History", "Geography", "Computer Science", "Art", "Hindi"];

export const mockContentItems = [
  {
    id: "c1",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Fractions Made Friendly",
    subject: "Mathematics",
    description: "Visual explanation of fraction equivalents for grade 5.",
    fileUrl: "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(-2),
    endTime: isoFromNow(8),
    rotationDuration: 12,
    createdAt: isoFromNow(-72)
  },
  {
    id: "c2",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Solar System Overview",
    subject: "Science",
    description: "Planet order and orbit labels for the hallway display.",
    fileUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "pending",
    rejectionReason: "",
    startTime: isoFromNow(5),
    endTime: isoFromNow(20),
    rotationDuration: 15,
    createdAt: isoFromNow(-24)
  },
  {
    id: "c3",
    teacherId: "t2",
    teacherName: "Amit Verma",
    title: "Indus Valley Timeline",
    subject: "History",
    description: "Key dates and discoveries for class 7 revision.",
    fileUrl: "https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(-5),
    endTime: isoFromNow(3),
    rotationDuration: 10,
    createdAt: isoFromNow(-96)
  },
  {
    id: "c4",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Reading Week Poster",
    subject: "English",
    description: "Announcement creative for library reading week.",
    fileUrl: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "rejected",
    rejectionReason: "Please add the school logo and correct the event date before rebroadcasting.",
    startTime: isoFromNow(-36),
    endTime: isoFromNow(-20),
    rotationDuration: 10,
    createdAt: isoFromNow(-120)
  },
  {
    id: "c5",
    teacherId: "t2",
    teacherName: "Amit Verma",
    title: "Map Skills: India",
    subject: "Geography",
    description: "States, rivers, and mountain ranges quick reference.",
    fileUrl: "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "pending",
    rejectionReason: "",
    startTime: isoFromNow(2),
    endTime: isoFromNow(28),
    rotationDuration: 14,
    createdAt: isoFromNow(-18)
  },
  {
    id: "c6",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Geometry Formula Board",
    subject: "Mathematics",
    description: "Area and perimeter formula recap with icons.",
    fileUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(-48),
    endTime: isoFromNow(-3),
    rotationDuration: 8,
    createdAt: isoFromNow(-168)
  },
  {
    id: "c7",
    teacherId: "t2",
    teacherName: "Amit Verma",
    title: "Coding Club Invite",
    subject: "Computer Science",
    description: "Registration details for the weekly coding club.",
    fileUrl: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(1),
    endTime: isoFromNow(40),
    rotationDuration: 20,
    createdAt: isoFromNow(-12)
  },
  {
    id: "c8",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Plant Cell Diagram",
    subject: "Science",
    description: "Labeled plant cell diagram for biology introduction.",
    fileUrl: "https://images.unsplash.com/photo-1530026186672-2cd00ffc50fe?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "pending",
    rejectionReason: "",
    startTime: isoFromNow(-1),
    endTime: isoFromNow(7),
    rotationDuration: 10,
    createdAt: isoFromNow(-8)
  },
  {
    id: "c9",
    teacherId: "t2",
    teacherName: "Amit Verma",
    title: "Water Conservation",
    subject: "Science",
    description: "Awareness poster for morning assembly screens.",
    fileUrl: "https://images.unsplash.com/photo-1527102935845-9c7e43932764?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "rejected",
    rejectionReason: "Image contrast is too low for corridor screens. Please upload a clearer version.",
    startTime: isoFromNow(-10),
    endTime: isoFromNow(2),
    rotationDuration: 12,
    createdAt: isoFromNow(-30)
  },
  {
    id: "c10",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Hindi Kavita Sandhya",
    subject: "Hindi",
    description: "Invitation slide for poetry recitation evening.",
    fileUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(10),
    endTime: isoFromNow(46),
    rotationDuration: 18,
    createdAt: isoFromNow(-6)
  },
  {
    id: "c11",
    teacherId: "t2",
    teacherName: "Amit Verma",
    title: "Grammar Quick Tips",
    subject: "English",
    description: "Common punctuation mistakes and corrections.",
    fileUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(-12),
    endTime: isoFromNow(14),
    rotationDuration: 9,
    createdAt: isoFromNow(-58)
  },
  {
    id: "c12",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Art Exhibition Preview",
    subject: "Art",
    description: "Student artwork collage for annual exhibition.",
    fileUrl: "https://images.unsplash.com/photo-1459908676235-d5f02a50184b?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "pending",
    rejectionReason: "",
    startTime: isoFromNow(24),
    endTime: isoFromNow(72),
    rotationDuration: 16,
    createdAt: isoFromNow(-3)
  },
  {
    id: "c13",
    teacherId: "t2",
    teacherName: "Amit Verma",
    title: "Algebra Identity Chart",
    subject: "Mathematics",
    description: "Core algebraic identities for daily revision.",
    fileUrl: "https://images.unsplash.com/photo-1596495578065-6e0763fa1178?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(-72),
    endTime: isoFromNow(-12),
    rotationDuration: 10,
    createdAt: isoFromNow(-180)
  },
  {
    id: "c14",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Lab Safety Rules",
    subject: "Science",
    description: "Safety icons and lab conduct reminders.",
    fileUrl: "https://images.unsplash.com/photo-1581093458791-9d15482442f6?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(-6),
    endTime: isoFromNow(18),
    rotationDuration: 12,
    createdAt: isoFromNow(-44)
  },
  {
    id: "c15",
    teacherId: "t2",
    teacherName: "Amit Verma",
    title: "Republic Day Practice",
    subject: "History",
    description: "Practice schedule and assembly instructions.",
    fileUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "pending",
    rejectionReason: "",
    startTime: isoFromNow(3),
    endTime: isoFromNow(30),
    rotationDuration: 15,
    createdAt: isoFromNow(-2)
  },
  {
    id: "c16",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Mental Math Challenge",
    subject: "Mathematics",
    description: "Daily challenge card for grade 6 students.",
    fileUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "rejected",
    rejectionReason: "Please remove student phone numbers from the lower section before approval.",
    startTime: isoFromNow(4),
    endTime: isoFromNow(22),
    rotationDuration: 11,
    createdAt: isoFromNow(-16)
  },
  {
    id: "c17",
    teacherId: "t2",
    teacherName: "Amit Verma",
    title: "Cloud Types",
    subject: "Geography",
    description: "Weather lesson visual with cloud classification.",
    fileUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(-1),
    endTime: isoFromNow(11),
    rotationDuration: 10,
    createdAt: isoFromNow(-20)
  },
  {
    id: "c18",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Essay Writing Checklist",
    subject: "English",
    description: "Step-by-step checklist for structured essays.",
    fileUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(-18),
    endTime: isoFromNow(9),
    rotationDuration: 13,
    createdAt: isoFromNow(-66)
  },
  {
    id: "c19",
    teacherId: "t2",
    teacherName: "Amit Verma",
    title: "Robotics Demo Day",
    subject: "Computer Science",
    description: "Demo day poster with venue and timing.",
    fileUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "pending",
    rejectionReason: "",
    startTime: isoFromNow(12),
    endTime: isoFromNow(48),
    rotationDuration: 18,
    createdAt: isoFromNow(-4)
  },
  {
    id: "c20",
    teacherId: "t1",
    teacherName: "Riya Sharma",
    title: "Monsoon Safety",
    subject: "Geography",
    description: "Safety advisory visual for rainy season.",
    fileUrl: "https://images.unsplash.com/photo-1519692933481-e162a57d6721?auto=format&fit=crop&w=900&q=80",
    fileType: "image/jpeg",
    status: "approved",
    rejectionReason: "",
    startTime: isoFromNow(-9),
    endTime: isoFromNow(15),
    rotationDuration: 12,
    createdAt: isoFromNow(-40)
  }
];
